In [1]:
# Dependencies and Setup
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
file_basic_path="data_sets/"
newFile = pd.ExcelFile("data_sets/climate_change_data.xls")
climchang_df = pd.read_excel("data_sets/climate_change_data.xls", sheet_name="Data")
climchang_df.columns

Index(['Country code', 'Country name',  'Series code',  'Series name',
              'SCALE',     'Decimals',           1990,           1991,
                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011],
      dtype='object')

In [3]:
co2_df=climchang_df[climchang_df['Series name']=='CO2 emissions per capita (metric tons)'].copy()
co2_df

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
1864,ABW,Aruba,EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,29.6206,29.8388,25.2393,24.4052,...,23.8404,23.2795,22.8063,22.5112,22.1353,22.623,21.6838,..,..,..
1865,ADO,Andorra,EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,..,..,..,..,...,7.70122,7.41496,7.50037,7.39163,6.84056,6.62304,6.52783,..,..,..
1866,AFG,Afghanistan,EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,0.140715,0.126777,0.0701453,0.0654029,...,0.0130843,0.0206349,0.0242207,0.0234208,0.0226567,0.0226127,0.0250348,..,..,..
1867,AGO,Angola,EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,0.428613,0.409949,0.401597,0.510141,...,0.850599,0.587864,1.17772,1.16177,1.30897,1.43517,1.35109,..,..,..
1868,ALB,Albania,EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,2.27635,1.20648,0.73071,0.7266,...,1.21411,1.38101,1.28145,1.46479,1.34059,1.41374,1.31286,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,YEM,"Yemen, Rep.",EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,-0.251051,0.806199,1.09035,0.680109,...,0.837117,0.891083,0.942838,0.970709,0.976692,1.00134,1.03349,..,..,..
2093,ZAF,South Africa,EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,9.47482,9.63839,8.85379,9.14103,...,7.63588,8.25758,8.87534,8.64857,8.49993,8.98017,8.9332,..,..,..
2094,ZAR,"Congo, Dem. Rep.",EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,0.111804,0.0991913,0.0917591,0.0830127,...,0.0294107,0.031384,0.040909,0.041255,0.041642,0.0419967,0.0450782,..,..,..
2095,ZMB,Zambia,EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,0.31118,0.299524,0.296995,0.29497,...,0.184148,0.192096,0.188389,0.197069,0.194427,0.14266,0.15255,..,..,..
2096,ZWE,Zimbabwe,EN.ATM.CO2E.PC,CO2 emissions per capita (metric tons),0,1,1.48092,1.47216,1.53568,1.44142,...,0.946432,0.842544,0.787956,0.857045,0.82561,0.77064,0.728892,..,..,..

In [4]:
co2_df.drop(['Country code', 'Series code','Series name','SCALE','Decimals',2009,2010,2011], axis=1, inplace = True)

In [5]:
co2_df

,Country name,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008
1864,Aruba,29.6206,29.8388,25.2393,24.4052,22.9779,22.2331,21.8071,21.7451,19.2162,19.0726,24.7389,24.2182,23.8404,23.2795,22.8063,22.5112,22.1353,22.623,21.6838
1865,Andorra,..,..,..,..,..,6.29124,6.52141,7.06224,7.53423,8.02344,8.11308,7.89849,7.70122,7.41496,7.50037,7.39163,6.84056,6.62304,6.52783
1866,Afghanistan,0.140715,0.126777,0.0701453,0.0654029,0.0607274,0.0564514,0.0518392,0.046827,0.043105,0.0330121,0.0300981,0.0241743,0.0130843,0.0206349,0.0242207,0.0234208,0.0226567,0.0226127,0.0250348
1867,Angola,0.428613,0.409949,0.401597,0.510141,0.331321,0.909699,0.842489,0.577043,0.556263,0.677678,0.685141,0.676401,0.850599,0.587864,1.17772,1.16177,1.30897,1.43517,1.35109
1868,Albania,2.27635,1.20648,0.73071,0.7266,0.606661,0.664265,0.647964,0.499307,0.569277,0.973817,0.98603,1.0498,1.21411,1.38101,1.28145,1.46479,1.34059,1.41374,1.31286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,"Yemen, Rep.",-0.251051,0.806199,1.09035,0.680109,0.782346,0.742687,0.9507,0.953645,0.729809,0.807407,0.825961,0.889748,0.837117,0.891083,0.942838,0.970709,0.976692,1.00134,1.03349
2093,South Africa,9.47482,9.63839,8.85379,9.14103,9.37564,9.03524,8.96594,9.07314,8.88357,8.64409,8.37751,8.07716,7.63588,8.25758,8.87534,8.64857,8.49993,8.98017,8.9332
2094,"Congo, Dem. Rep.",0.111804,0.0991913,0.0917591,0.0830127,0.0581214,0.0673197,0.0717289,0.0631078,0.0534875,0.046415,0.0331777,0.0307085,0.0294107,0.031384,0.040909,0.041255,0.041642,0.0419967,0.0450782
2095,Zambia,0.31118,0.299524,0.296995,0.29497,0.278423,0.243385,0.204124,0.25386,0.238986,0.181781,0.17829,0.182476,0.184148,0.192096,0.188389,0.197069,0.194427,0.14266,0.15255
2096,Zimbabwe,1.48092,1.47216,1.53568,1.44142,1.53843,1.29486,1.26095,1.19204,1.16245,1.27641,1.11011,0.999056,0.946432,0.842544,0.787956,0.857045,0.82561,0.77064,0.728892

In [6]:
#swaping index and column values around
co2_df_transposed = co2_df.transpose().copy()
co2_df_transposed

,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,...,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096
Country name,Aruba,Andorra,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,American Samoa,Antigua and Barbuda,...,Vietnam,Vanuatu,West Bank and Gaza,World,Samoa,"Yemen, Rep.",South Africa,"Congo, Dem. Rep.",Zambia,Zimbabwe
1990,29.6206,..,0.140715,0.428613,2.27635,28.7559,3.44991,..,..,4.83415,...,0.324281,0.475143,..,4.27322,0.772919,-0.251051,9.47482,0.111804,0.31118,1.48092
1991,29.8388,..,0.126777,0.409949,1.20648,29.8516,3.53607,..,..,4.67476,...,0.319024,0.437732,..,4.26775,0.76723,0.806199,9.63839,0.0991913,0.299524,1.47216
1992,25.2393,..,0.0701453,0.401597,0.73071,28.8649,3.62097,1.06717,..,4.59797,...,0.327056,0.425105,..,4.12706,0.783595,1.09035,8.85379,0.0917591,0.296995,1.53568
1993,24.4052,..,0.0654029,0.510141,0.7266,31.0978,3.49035,0.86932,..,4.7216,...,0.329819,0.412907,..,4.07002,0.777038,0.680109,9.14103,0.0830127,0.29497,1.44142
1994,22.9779,..,0.0607274,0.331321,0.606661,32.7504,3.58365,0.901555,..,4.65947,...,0.371388,0.401853,..,4.08815,0.726086,0.782346,9.37564,0.0581214,0.278423,1.53843
1995,22.2331,6.29124,0.0564514,0.909699,0.664265,30.0787,3.51591,1.08309,..,4.70115,...,0.406248,0.392279,..,4.11825,0.784585,0.742687,9.03524,0.0673197,0.243385,1.29486
1996,21.8071,6.52141,0.0518392,0.842489,0.647964,16.5965,3.6619,0.821906,..,4.5805,...,0.469924,0.490974,..,4.14824,0.776683,0.9507,8.96594,0.0717289,0.204124,1.26095
1997,21.7451,7.06224,0.046827,0.577043,0.499307,15.9465,3.77091,1.04576,..,4.66475,...,0.609416,0.50313,0.153101,4.16958,0.768557,0.953645,9.07314,0.0631078,0.25386,1.19204
1998,19.2162,7.53423,0.043105,0.556263,0.569277,29.5756,3.81002,1.0957,..,4.49787,...,0.633228,0.47397,0.217222,4.10175,0.760688,0.729809,8.88357,0.0534875,0.238986,1.16245
1999,19.0726,8.02344,0.0330121,0.677678,0.973817,27.0534,3.9815,0.989534,..,4.58465,...,0.627007,0.465358,0.227492,4.01198,0.795495,0.807407,8.64409,0.046415,0.181781,1.27641
2000,24.7389,8.11308,0.0300981,0.685141,0.98603,37.1065,3.82004,1.12653,..,4.43878,...,0.690217,0.435901,0.266101,4.0607,0.789277,0.825961,8.37751,0.0331777,0.17829,1.11011
2001,24.2182,7.89849,0.0241743,0.676401,1.0498,32.1752,3.76579,1.15543,..,4.35417,...,0.783903,0.444968,0.435023,4.10619,0.805049,0.889748,8.07716,0.0307085,0.182476,0.999056
2002,23.8404,7.70122,0.0130843,0.850599,1.21411,25.9013,3.48954,0.98112,..,4.50933,...,0.897033,0.433507,0.362084,4.08847,0.801247,0.837117,7.63588,0.0294107,0.184148,0.946432
2003,23.2795,7.41496,0.0206349,0.587864,1.38101,31.275,3.74591,1.12027,..,4.75674,...,0.987198,0.44011,0.383799,4.23366,0.839266,0.891083,8.25758,0.031384,0.192096,0.842544
2004,22.8063,7.50037,0.0242207,1.17772,1.28145,30.8574,4.0427,1.19016,..,4.91365,...,1.24854,0.428136,0.540621,4.40308,0.857067,0.942838,8.87534,0.040909,0.188389,0.787956
2005,22.5112,7.39163,0.0234208,1.16177,1.46479,28.4143,4.10856,1.4185,..,4.89423,...,1.26326,0.260477,0.767314,4.52216,0.874854,0.970709,8.64857,0.041255,0.197069,0.857045
2006,22.1353,6.84056,0.0226567,1.30897,1.34059,26.3264,4.49797,1.42626,..,5.0072,...,1.00508,0.219925,0.612289,4.61226,0.872293,0.976692,8.49993,0.041642,0.194427,0.82561
2007,22.623,6.62304,0.0226127,1.43517,1.41374,25.526,4.66692,1.64492,..,5.07794,...,1.33329,0.36278,0.606672,4.6368,0.890063,1.00134,8.98017,0.0419967,0.14266,0.77064
2008,21.6838,6.52783,0.0250348,1.35109,1.31286,24.984,4.84405,1.80189,..,5.14927,...,1.49649,0.402011,0.521554,..,0.887459,1.03349,8.9332,0.0450782,0.15255,0.728892

In [7]:
co2_df_transposed.reset_index(drop = False, inplace = True)

In [8]:
#making row index 0 into column titles
co2_df_transposed.columns = co2_df_transposed.iloc[0,:]

In [9]:
co2_df_transposed

,Country name,Aruba,Andorra,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,American Samoa,...,Vietnam,Vanuatu,West Bank and Gaza,World,Samoa,"Yemen, Rep.",South Africa,"Congo, Dem. Rep.",Zambia,Zimbabwe
0,Country name,Aruba,Andorra,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,American Samoa,...,Vietnam,Vanuatu,West Bank and Gaza,World,Samoa,"Yemen, Rep.",South Africa,"Congo, Dem. Rep.",Zambia,Zimbabwe
1,1990,29.6206,..,0.140715,0.428613,2.27635,28.7559,3.44991,..,..,...,0.324281,0.475143,..,4.27322,0.772919,-0.251051,9.47482,0.111804,0.31118,1.48092
2,1991,29.8388,..,0.126777,0.409949,1.20648,29.8516,3.53607,..,..,...,0.319024,0.437732,..,4.26775,0.76723,0.806199,9.63839,0.0991913,0.299524,1.47216
3,1992,25.2393,..,0.0701453,0.401597,0.73071,28.8649,3.62097,1.06717,..,...,0.327056,0.425105,..,4.12706,0.783595,1.09035,8.85379,0.0917591,0.296995,1.53568
4,1993,24.4052,..,0.0654029,0.510141,0.7266,31.0978,3.49035,0.86932,..,...,0.329819,0.412907,..,4.07002,0.777038,0.680109,9.14103,0.0830127,0.29497,1.44142
5,1994,22.9779,..,0.0607274,0.331321,0.606661,32.7504,3.58365,0.901555,..,...,0.371388,0.401853,..,4.08815,0.726086,0.782346,9.37564,0.0581214,0.278423,1.53843
6,1995,22.2331,6.29124,0.0564514,0.909699,0.664265,30.0787,3.51591,1.08309,..,...,0.406248,0.392279,..,4.11825,0.784585,0.742687,9.03524,0.0673197,0.243385,1.29486
7,1996,21.8071,6.52141,0.0518392,0.842489,0.647964,16.5965,3.6619,0.821906,..,...,0.469924,0.490974,..,4.14824,0.776683,0.9507,8.96594,0.0717289,0.204124,1.26095
8,1997,21.7451,7.06224,0.046827,0.577043,0.499307,15.9465,3.77091,1.04576,..,...,0.609416,0.50313,0.153101,4.16958,0.768557,0.953645,9.07314,0.0631078,0.25386,1.19204
9,1998,19.2162,7.53423,0.043105,0.556263,0.569277,29.5756,3.81002,1.0957,..,...,0.633228,0.47397,0.217222,4.10175,0.760688,0.729809,8.88357,0.0534875,0.238986,1.16245
10,1999,19.0726,8.02344,0.0330121,0.677678,0.973817,27.0534,3.9815,0.989534,..,...,0.627007,0.465358,0.227492,4.01198,0.795495,0.807407,8.64409,0.046415,0.181781,1.27641
11,2000,24.7389,8.11308,0.0300981,0.685141,0.98603,37.1065,3.82004,1.12653,..,...,0.690217,0.435901,0.266101,4.0607,0.789277,0.825961,8.37751,0.0331777,0.17829,1.11011
12,2001,24.2182,7.89849,0.0241743,0.676401,1.0498,32.1752,3.76579,1.15543,..,...,0.783903,0.444968,0.435023,4.10619,0.805049,0.889748,8.07716,0.0307085,0.182476,0.999056
13,2002,23.8404,7.70122,0.0130843,0.850599,1.21411,25.9013,3.48954,0.98112,..,...,0.897033,0.433507,0.362084,4.08847,0.801247,0.837117,7.63588,0.0294107,0.184148,0.946432
14,2003,23.2795,7.41496,0.0206349,0.587864,1.38101,31.275,3.74591,1.12027,..,...,0.987198,0.44011,0.383799,4.23366,0.839266,0.891083,8.25758,0.031384,0.192096,0.842544
15,2004,22.8063,7.50037,0.0242207,1.17772,1.28145,30.8574,4.0427,1.19016,..,...,1.24854,0.428136,0.540621,4.40308,0.857067,0.942838,8.87534,0.040909,0.188389,0.787956
16,2005,22.5112,7.39163,0.0234208,1.16177,1.46479,28.4143,4.10856,1.4185,..,...,1.26326,0.260477,0.767314,4.52216,0.874854,0.970709,8.64857,0.041255,0.197069,0.857045
17,2006,22.1353,6.84056,0.0226567,1.30897,1.34059,26.3264,4.49797,1.42626,..,...,1.00508,0.219925,0.612289,4.61226,0.872293,0.976692,8.49993,0.041642,0.194427,0.82561
18,2007,22.623,6.62304,0.0226127,1.43517,1.41374,25.526,4.66692,1.64492,..,...,1.33329,0.36278,0.606672,4.6368,0.890063,1.00134,8.98017,0.0419967,0.14266,0.77064
19,2008,21.6838,6.52783,0.0250348,1.35109,1.31286,24.984,4.84405,1.80189,..,...,1.49649,0.402011,0.521554,..,0.887459,1.03349,8.9332,0.0450782,0.15255,0.728892

In [10]:
#removing country name column
co2_df_transposed = co2_df_transposed.drop(0)

In [13]:
#Changing name from country name to year

co2_df_transposed = co2_df_transposed.rename(columns = {"Country name":"Year"})

In [14]:
co2_df_transposed

,Year,Aruba,Andorra,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,American Samoa,...,Vietnam,Vanuatu,West Bank and Gaza,World,Samoa,"Yemen, Rep.",South Africa,"Congo, Dem. Rep.",Zambia,Zimbabwe
1,1990,29.6206,..,0.140715,0.428613,2.27635,28.7559,3.44991,..,..,...,0.324281,0.475143,..,4.27322,0.772919,-0.251051,9.47482,0.111804,0.31118,1.48092
2,1991,29.8388,..,0.126777,0.409949,1.20648,29.8516,3.53607,..,..,...,0.319024,0.437732,..,4.26775,0.76723,0.806199,9.63839,0.0991913,0.299524,1.47216
3,1992,25.2393,..,0.0701453,0.401597,0.73071,28.8649,3.62097,1.06717,..,...,0.327056,0.425105,..,4.12706,0.783595,1.09035,8.85379,0.0917591,0.296995,1.53568
4,1993,24.4052,..,0.0654029,0.510141,0.7266,31.0978,3.49035,0.86932,..,...,0.329819,0.412907,..,4.07002,0.777038,0.680109,9.14103,0.0830127,0.29497,1.44142
5,1994,22.9779,..,0.0607274,0.331321,0.606661,32.7504,3.58365,0.901555,..,...,0.371388,0.401853,..,4.08815,0.726086,0.782346,9.37564,0.0581214,0.278423,1.53843
6,1995,22.2331,6.29124,0.0564514,0.909699,0.664265,30.0787,3.51591,1.08309,..,...,0.406248,0.392279,..,4.11825,0.784585,0.742687,9.03524,0.0673197,0.243385,1.29486
7,1996,21.8071,6.52141,0.0518392,0.842489,0.647964,16.5965,3.6619,0.821906,..,...,0.469924,0.490974,..,4.14824,0.776683,0.9507,8.96594,0.0717289,0.204124,1.26095
8,1997,21.7451,7.06224,0.046827,0.577043,0.499307,15.9465,3.77091,1.04576,..,...,0.609416,0.50313,0.153101,4.16958,0.768557,0.953645,9.07314,0.0631078,0.25386,1.19204
9,1998,19.2162,7.53423,0.043105,0.556263,0.569277,29.5756,3.81002,1.0957,..,...,0.633228,0.47397,0.217222,4.10175,0.760688,0.729809,8.88357,0.0534875,0.238986,1.16245
10,1999,19.0726,8.02344,0.0330121,0.677678,0.973817,27.0534,3.9815,0.989534,..,...,0.627007,0.465358,0.227492,4.01198,0.795495,0.807407,8.64409,0.046415,0.181781,1.27641
11,2000,24.7389,8.11308,0.0300981,0.685141,0.98603,37.1065,3.82004,1.12653,..,...,0.690217,0.435901,0.266101,4.0607,0.789277,0.825961,8.37751,0.0331777,0.17829,1.11011
12,2001,24.2182,7.89849,0.0241743,0.676401,1.0498,32.1752,3.76579,1.15543,..,...,0.783903,0.444968,0.435023,4.10619,0.805049,0.889748,8.07716,0.0307085,0.182476,0.999056
13,2002,23.8404,7.70122,0.0130843,0.850599,1.21411,25.9013,3.48954,0.98112,..,...,0.897033,0.433507,0.362084,4.08847,0.801247,0.837117,7.63588,0.0294107,0.184148,0.946432
14,2003,23.2795,7.41496,0.0206349,0.587864,1.38101,31.275,3.74591,1.12027,..,...,0.987198,0.44011,0.383799,4.23366,0.839266,0.891083,8.25758,0.031384,0.192096,0.842544
15,2004,22.8063,7.50037,0.0242207,1.17772,1.28145,30.8574,4.0427,1.19016,..,...,1.24854,0.428136,0.540621,4.40308,0.857067,0.942838,8.87534,0.040909,0.188389,0.787956
16,2005,22.5112,7.39163,0.0234208,1.16177,1.46479,28.4143,4.10856,1.4185,..,...,1.26326,0.260477,0.767314,4.52216,0.874854,0.970709,8.64857,0.041255,0.197069,0.857045
17,2006,22.1353,6.84056,0.0226567,1.30897,1.34059,26.3264,4.49797,1.42626,..,...,1.00508,0.219925,0.612289,4.61226,0.872293,0.976692,8.49993,0.041642,0.194427,0.82561
18,2007,22.623,6.62304,0.0226127,1.43517,1.41374,25.526,4.66692,1.64492,..,...,1.33329,0.36278,0.606672,4.6368,0.890063,1.00134,8.98017,0.0419967,0.14266,0.77064
19,2008,21.6838,6.52783,0.0250348,1.35109,1.31286,24.984,4.84405,1.80189,..,...,1.49649,0.402011,0.521554,..,0.887459,1.03349,8.9332,0.0450782,0.15255,0.728892

In [15]:
# Dependencies and Setup
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

file_basic_path="data_sets/"
newFile = pd.ExcelFile("data_sets/climate_change_data.xls")
climchang_df = pd.read_excel("data_sets/climate_change_data.xls", sheet_name="Data")
climchang_df.columns

co2_df=climchang_df[climchang_df['Series name']=='CO2 emissions per capita (metric tons)'].copy()
co2_df

co2_df.drop(['Country code', 'Series code','Series name','SCALE','Decimals',2009,2010,2011], axis=1, inplace = True)


co2_df

#swaping index and column values around
co2_df_transposed = co2_df.transpose().copy()
co2_df_transposed

co2_df_transposed.reset_index(drop = False, inplace = True)

#making row index 0 into column titles
co2_df_transposed.columns = co2_df_transposed.iloc[0,:]

co2_df_transposed

#removing country name column
co2_df_transposed = co2_df_transposed.drop(0)

#Changing name from country name to year

co2_df_transposed = co2_df_transposed.rename(columns = {"Country name":"Year"})

co2_df_transposed

,Year,Aruba,Andorra,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,American Samoa,...,Vietnam,Vanuatu,West Bank and Gaza,World,Samoa,"Yemen, Rep.",South Africa,"Congo, Dem. Rep.",Zambia,Zimbabwe
1,1990,29.6206,..,0.140715,0.428613,2.27635,28.7559,3.44991,..,..,...,0.324281,0.475143,..,4.27322,0.772919,-0.251051,9.47482,0.111804,0.31118,1.48092
2,1991,29.8388,..,0.126777,0.409949,1.20648,29.8516,3.53607,..,..,...,0.319024,0.437732,..,4.26775,0.76723,0.806199,9.63839,0.0991913,0.299524,1.47216
3,1992,25.2393,..,0.0701453,0.401597,0.73071,28.8649,3.62097,1.06717,..,...,0.327056,0.425105,..,4.12706,0.783595,1.09035,8.85379,0.0917591,0.296995,1.53568
4,1993,24.4052,..,0.0654029,0.510141,0.7266,31.0978,3.49035,0.86932,..,...,0.329819,0.412907,..,4.07002,0.777038,0.680109,9.14103,0.0830127,0.29497,1.44142
5,1994,22.9779,..,0.0607274,0.331321,0.606661,32.7504,3.58365,0.901555,..,...,0.371388,0.401853,..,4.08815,0.726086,0.782346,9.37564,0.0581214,0.278423,1.53843
6,1995,22.2331,6.29124,0.0564514,0.909699,0.664265,30.0787,3.51591,1.08309,..,...,0.406248,0.392279,..,4.11825,0.784585,0.742687,9.03524,0.0673197,0.243385,1.29486
7,1996,21.8071,6.52141,0.0518392,0.842489,0.647964,16.5965,3.6619,0.821906,..,...,0.469924,0.490974,..,4.14824,0.776683,0.9507,8.96594,0.0717289,0.204124,1.26095
8,1997,21.7451,7.06224,0.046827,0.577043,0.499307,15.9465,3.77091,1.04576,..,...,0.609416,0.50313,0.153101,4.16958,0.768557,0.953645,9.07314,0.0631078,0.25386,1.19204
9,1998,19.2162,7.53423,0.043105,0.556263,0.569277,29.5756,3.81002,1.0957,..,...,0.633228,0.47397,0.217222,4.10175,0.760688,0.729809,8.88357,0.0534875,0.238986,1.16245
10,1999,19.0726,8.02344,0.0330121,0.677678,0.973817,27.0534,3.9815,0.989534,..,...,0.627007,0.465358,0.227492,4.01198,0.795495,0.807407,8.64409,0.046415,0.181781,1.27641
11,2000,24.7389,8.11308,0.0300981,0.685141,0.98603,37.1065,3.82004,1.12653,..,...,0.690217,0.435901,0.266101,4.0607,0.789277,0.825961,8.37751,0.0331777,0.17829,1.11011
12,2001,24.2182,7.89849,0.0241743,0.676401,1.0498,32.1752,3.76579,1.15543,..,...,0.783903,0.444968,0.435023,4.10619,0.805049,0.889748,8.07716,0.0307085,0.182476,0.999056
13,2002,23.8404,7.70122,0.0130843,0.850599,1.21411,25.9013,3.48954,0.98112,..,...,0.897033,0.433507,0.362084,4.08847,0.801247,0.837117,7.63588,0.0294107,0.184148,0.946432
14,2003,23.2795,7.41496,0.0206349,0.587864,1.38101,31.275,3.74591,1.12027,..,...,0.987198,0.44011,0.383799,4.23366,0.839266,0.891083,8.25758,0.031384,0.192096,0.842544
15,2004,22.8063,7.50037,0.0242207,1.17772,1.28145,30.8574,4.0427,1.19016,..,...,1.24854,0.428136,0.540621,4.40308,0.857067,0.942838,8.87534,0.040909,0.188389,0.787956
16,2005,22.5112,7.39163,0.0234208,1.16177,1.46479,28.4143,4.10856,1.4185,..,...,1.26326,0.260477,0.767314,4.52216,0.874854,0.970709,8.64857,0.041255,0.197069,0.857045
17,2006,22.1353,6.84056,0.0226567,1.30897,1.34059,26.3264,4.49797,1.42626,..,...,1.00508,0.219925,0.612289,4.61226,0.872293,0.976692,8.49993,0.041642,0.194427,0.82561
18,2007,22.623,6.62304,0.0226127,1.43517,1.41374,25.526,4.66692,1.64492,..,...,1.33329,0.36278,0.606672,4.6368,0.890063,1.00134,8.98017,0.0419967,0.14266,0.77064
19,2008,21.6838,6.52783,0.0250348,1.35109,1.31286,24.984,4.84405,1.80189,..,...,1.49649,0.402011,0.521554,..,0.887459,1.03349,8.9332,0.0450782,0.15255,0.728892